include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    avoid_print: false
    # Calling toString on a runtime type is a non-trivial
    # operation that can negatively impact performance.
    # Eat me.
    no_runtimeType_toString: false
    # Of course the comparison of unrelated should return false
    unrelated_type_equality_checks: false
    # better to have this deactivated for beginners
    prefer_const_constructors: true
    avoid_classes_with_only_static_members: false